// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1567975328);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1567975448);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1567975208);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1567975688);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1567975568);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.countryCode", "FR");
user_pref("browser.search.region", "FR");
user_pref("calendar.list.sortOrder", "265c13fb-9dcb-4250-aa27-aa4abd64402c");
user_pref("calendar.registry.265c13fb-9dcb-4250-aa27-aa4abd64402c.calendar-main-default", true);
user_pref("calendar.registry.265c13fb-9dcb-4250-aa27-aa4abd64402c.calendar-main-in-composite", true);
user_pref("calendar.registry.265c13fb-9dcb-4250-aa27-aa4abd64402c.name", "Home");
user_pref("calendar.registry.265c13fb-9dcb-4250-aa27-aa4abd64402c.type", "storage");
user_pref("calendar.registry.265c13fb-9dcb-4250-aa27-aa4abd64402c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Paris");
user_pref("calendar.ui.version", 3);
user_pref("extensions.blocklist.lastModified", "Wed, 28 Aug 2019 19:55:12 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1567975328);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installedDistroAddon.{e2fda1a4-762b-4020-b5ad-a41df1933103}", true);
user_pref("extensions.lastAppVersion", "60.8.0");
user_pref("extensions.lastPlatformVersion", "60.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"9910a764-0638-4cf1-8e2b-6026ced89233\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.account.lastKey", 2);
user_pref("mail.accountmanager.accounts", "account1,account2");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.localfoldersserver", "server2");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.identity.id1.archive_folder", "imap://$USER%40epita.fr@outlook.office365.com/Archives");
// Disable HTML composition to be compliant regarding the Netiquette
user_pref("mail.identity.id1.compose_html", false);
user_pref("mail.identity.id1.doBcc", false);
user_pref("mail.identity.id1.draft_folder", "imap://$USER%40epita.fr@outlook.office365.com/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "0");
user_pref("mail.identity.id1.fcc_folder", "imap://$USER%40epita.fr@outlook.office365.com/&AMk-l&AOk-ments envoy&AOk-s");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "1");
user_pref("mail.identity.id1.fullName", "Anis Ladram");
user_pref("mail.identity.id1.reply_on_top", 1);
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.stationery_folder", "imap://$USER%40epita.fr@outlook.office365.com/Templates");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id1.useremail", "$USER@epita.fr");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.purge_threshold_migrated", true);
user_pref("mail.root.imap", "$HOME/.thunderbird/piq5izo7.default/ImapMail");
user_pref("mail.root.imap-rel", "[ProfD]ImapMail");
user_pref("mail.root.none", "$HOME/.thunderbird/piq5izo7.default/Mail");
user_pref("mail.root.none-rel", "[ProfD]Mail");
user_pref("mail.server.server1.ageLimit", 30);
user_pref("mail.server.server1.applyToFlaggedMessages", false);
user_pref("mail.server.server1.cacheCapa.acl", false);
user_pref("mail.server.server1.cacheCapa.quota", false);
user_pref("mail.server.server1.check_new_mail", true);
user_pref("mail.server.server1.cleanupBodies", false);
user_pref("mail.server.server1.daysToKeepBodies", 30);
user_pref("mail.server.server1.daysToKeepHdrs", 30);
user_pref("mail.server.server1.directory", "$HOME/.thunderbird/piq5izo7.default/ImapMail/outlook.office365.com");
user_pref("mail.server.server1.directory-rel", "[ProfD]ImapMail/outlook.office365.com");
user_pref("mail.server.server1.downloadByDate", false);
user_pref("mail.server.server1.downloadUnreadOnly", false);
user_pref("mail.server.server1.force_select", "no-auto");
user_pref("mail.server.server1.hostname", "outlook.office365.com");
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.server.server1.max_cached_connections", 5);
user_pref("mail.server.server1.moveTargetMode", 1);
user_pref("mail.server.server1.name", "$USER@epita.fr");
user_pref("mail.server.server1.namespace.personal", "\"\"");
user_pref("mail.server.server1.numHdrsToKeep", 2000);
/* 
 * Only download messages headers to prevent Thunderbird from downloading
 * messages to the AFS
 */
user_pref("mail.server.server1.offline_download", false);
user_pref("mail.server.server1.port", 993);
user_pref("mail.server.server1.serverIDResponse", "(\"name\" \"Microsoft.Exchange.Imap4.Imap4Server\" \"version\" \"15.20\")");
user_pref("mail.server.server1.socketType", 3);
user_pref("mail.server.server1.spamActionTargetAccount", "imap://$USER%40epita.fr@outlook.office365.com");
user_pref("mail.server.server1.spamActionTargetFolder", "imap://$USER%40epita.fr@outlook.office365.com/Courrier ind&AOk-sirable");
user_pref("mail.server.server1.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server1.timeout", 29);
user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.userName", "$USER@epita.fr");
user_pref("mail.server.server2.directory", "$HOME/.thunderbird/piq5izo7.default/Mail/Local Folders");
user_pref("mail.server.server2.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server2.hostname", "Local Folders");
user_pref("mail.server.server2.name", "Local Folders");
user_pref("mail.server.server2.spamActionTargetAccount", "mailbox://nobody@Local%20Folders");
user_pref("mail.server.server2.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server2.type", "none");
user_pref("mail.server.server2.userName", "nobody");
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.description", "Outlook.com (Microsoft)");
user_pref("mail.smtpserver.smtp1.hostname", "smtp.office365.com");
user_pref("mail.smtpserver.smtp1.port", 587);
user_pref("mail.smtpserver.smtp1.try_ssl", 2);
user_pref("mail.smtpserver.smtp1.username", "$USER@epita.fr");
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.spam.version", 1);
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "458eef20-4ac1-4604-a4c1-8442e8cda14");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "60.8.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("services.blocklist.addons.checked", 1567975392);
user_pref("services.blocklist.clock_skew_seconds", 56);
user_pref("services.blocklist.gfx.checked", 1567975392);
user_pref("services.blocklist.last_etag", "\"1567814407663\"");
user_pref("services.blocklist.last_update_seconds", 1567975392);
user_pref("services.blocklist.onecrl.checked", 1567975392);
user_pref("services.blocklist.pinning.checked", 1567975392);
user_pref("services.blocklist.plugins.checked", 1567975392);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "f771f61c-5509-4158-aa21-2a1851879012");
user_pref("toolkit.telemetry.previousBuildID", "20190714102313");
user_pref("toolkit.telemetry.prompted", 2);
